### ISSUE TITLE
Change slider mouse cursor

### ISSUE THREAD

**Issue by fredrikj31** [aptabase/aptabase-com#3]
Hi.

When I scrolled through your website, I saw that the pricing slider didn't have a different mouse cursor, when you were hovering over the slider button. I don't know if the mouse cursor should change, but I think it would be better (also for accessibility reasons) to have another mouse cursor when you are hovering or sliding the blue circle on the slider. 

![image](https://github.com/aptabase/aptabase-com/assets/31306224/1f2ef160-f342-4829-973d-e13fe74214c1)

The mouse cursor could maybe be changed to the `grab` one, which I think is appropriate to the slider. 
List of the different mouse cursors: https://www.w3schools.com/cssref/tryit.php?filename=trycss_cursor

Let me know if you want this changed. I can make a PR on it, if you are open for Pull Requests 😄

**Comment by goenning** [comment]
I like the idea of using the grab cursor. Would you like to send a PR?

**Comment by fredrikj31** [comment]
Yes, I would love to send a PR. I'll begin to work on it 👍

**Comment by fredrikj31** [comment]
PR has been created #4 @goenning
