### ISSUE TITLE
[BUG] Support buttons are broken

### ISSUE THREAD

**Issue by GabrielRozendo** [aptabase/aptabase-com#5]
When logged in (https://eu.aptabase.com/) , where I can choose the "my apps" and dashboard

In the "support" section, the "Help" and "Feedback" buttons are broken. No action.
Tried on Safari and Chrome (Mac)

![CleanShot 2023-09-26 at 10 45 21@2x](https://github.com/aptabase/aptabase-com/assets/18291470/144ff6e2-90e4-4c59-87d8-13e1ac17987d)

**Comment by goenning** [comment]
Those buttons should open the chat window on the bottom right, is that not working for you?

On page load, however, we delay that script for 5 seconds to prioritise the rest of the UI, including the charts/dashboard. I might need to rethink this 🤔 

![Screenshot 2023-09-26 at 11 52 18](https://github.com/aptabase/aptabase-com/assets/94755/2b4911bd-eacc-4f42-b366-d715520cf1ae)

**Comment by GabrielRozendo** [comment]
got it!
well, it's not working here in both browsers.

Indeed after 5 seconds there are new fetch here and the warning appears.
but still not working. 

I've just reloaded the page, waited the GET (all 200) and then clicked in both links, nothing happened.
checked Adblock tab and nothing there.

![CleanShot 2023-09-26 at 14 40 00](https://github.com/aptabase/aptabase-com/assets/18291470/a1e0d69f-315a-4a57-9e7b-79d9e18f01df)


tried in iPad and worked.
tried in Safari `without content blockers` and worked.

so it's something about local blockers here. 
![CleanShot 2023-09-26 at 14 49 20](https://github.com/aptabase/aptabase-com/assets/18291470/49647800-984d-4e19-8469-b6344cacc6c1)


Sorry and thank you!
